name: Bump Chart

on:
  push:
    branches: [master]
    paths: [charts/app/**]

#  workflow_dispatch:
#    inputs:
#      chart:
#        description: Selected chart to bump
#        required: true
#        default: app
#        type: choice
#        options:
#          - app
#          - staking
#      chart-version:
#        description: Chart version
#        type: choice
#        options:
#          - ""
#          - patch
#          - minor
#          - major
#      app-version:
#        description: App version
#        type: choice
#        options:
#          - ""
#          - patch
#          - minor
#          - major

jobs:
  bump:
    name: Bump chart
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions [Bot]"

      - name: Install yq
        run: sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

      - name: Get current chart version
        id: version
        run: echo "chart=$(yq '.version' charts/app/Chart.yaml)" >> $GITHUB_OUTPUT

      - name: Get next version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.version.outputs.chart }}

      - name: Set next patch chart version
#        if: ${{ contains('fix') }}
        run: |
          echo ${{ github.event.head_commit.message }}
          echo ${{ github.event.workflow_run.head_commit.message }}
#          yq -i '.version = "${{ steps.semvers.outputs.patch }}"' charts/app/Chart.yaml
#          yq '.version' charts/app/Chart.yaml

#      - name: Bump
#        run: |
#           echo ${{ steps.version.outputs.chart }}
#           echo ${{ steps.version.outputs.app }}

#          echo ${{ steps.chart-version.outputs.result }}
#          echo ${{ steps.app-version.outputs.result }}
#          echo ${{ steps.semvers.outputs.patch }}
#          echo ${{ steps.semvers.outputs.minor }}
#          echo ${{ steps.semvers.outputs.v_patch }}
#          echo ${{ steps.semvers.outputs.v_minor }}


